# Generated by Django 3.0.4 on 2020-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.CharField(choices=[('WB', 'Sites'), ('VD', 'Vídeos'), ('IP', 'Impressos'), ('LR', 'Lyric Videos')], default='WB', max_length=2),
        ),
    ]
