# Generated by Django 3.0.4 on 2020-03-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_work_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='work'),
        ),
    ]
