# Generated by Django 3.0.4 on 2020-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='categories',
            field=models.CharField(choices=[('MO', 'Montanhas'), ('ES', 'Escaladas'), ('EX', 'Expedições'), ('AR', 'Lyric Artigos')], default='MO', max_length=2),
        ),
    ]
